site_name: Keras Documentation
theme: readthedocs
# theme_dir: theme
docs_dir: sources
repo_url: http://github.com/keras-team/keras
site_url: http://keras.io/
site_description: 'Documentation for Keras, the Python Deep Learning library.'

dev_addr: '0.0.0.0:8000'
google_analytics: ['UA-61785484-1', 'keras.io']

pages:
- 대문: index.md
- Why use Keras: why-use-keras.md
- 배워 보기:
  - 순차 모델 소개: getting-started/sequential-model-guide.md
  - 함수형 API 소개: getting-started/functional-api-guide.md
  - FAQ: getting-started/faq.md
- Models:
  - About Keras models: models/about-keras-models.md
  - Sequential: models/sequential.md
  - Model (functional API): models/model.md
- 층:
  - 케라스 층에 대해: layers/about-keras-layers.md
  - Core Layers: layers/core.md
  - Convolutional Layers: layers/convolutional.md
  - Pooling Layers: layers/pooling.md
  - Locally-connected Layers: layers/local.md
  - Recurrent Layers: layers/recurrent.md
  - Embedding Layers: layers/embeddings.md
  - Merge Layers: layers/merge.md
  - Advanced Activations Layers: layers/advanced-activations.md
  - Normalization Layers: layers/normalization.md
  - Noise layers: layers/noise.md
  - Layer wrappers: layers/wrappers.md
  - Writing your own Keras layers: layers/writing-your-own-keras-layers.md
- Preprocessing:
  - Sequence Preprocessing: preprocessing/sequence.md
  - Text Preprocessing: preprocessing/text.md
  - Image Preprocessing: preprocessing/image.md
- 손실: losses.md
- 측정: metrics.md
- Optimizers: optimizers.md
- Activations: activations.md
- Callbacks: callbacks.md
- Datasets: datasets.md
- Applications: applications.md
- Backend: backend.md
- Initializers: initializers.md
- Regularizers: regularizers.md
- Constraints: constraints.md
- Visualization: visualization.md
- Scikit-learn API: scikit-learn-api.md
- Utils: utils.md
- Contributing: contributing.md
